### ISSUE TITLE
Xcode 6 beta 6

### ISSUE THREAD

**Issue by m4rr** [seivan/ScalarArithmetic#13]
Swift compiler error: '__conversion' functions are no longer allowed.

(I am trying to find a solution, but may be you knows better.)

**Comment by okachobi** [comment]
Decent fix not possible?

**Comment by raygun101** [comment]
Looks to me like implicit conversion isn't possible anymore?

**Comment by seivan** [comment]
@raygun101 conversion, no. But you can still have expectations(?). Checkout the new ones for 2.2.
